CREATE SCHEMA IF NOT EXISTS "argo";
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "argo"."daily_metrics" (
	"date" text PRIMARY KEY NOT NULL,
	"steps" integer,
	"distance_m" integer,
	"total_kcal" real,
	"active_kcal" real,
	"floors_ascended" real,
	"moderate_intensity_min" integer,
	"vigorous_intensity_min" integer,
	"resting_hr" integer,
	"max_hr" integer,
	"min_hr" integer,
	"hrv_last_night_avg" integer,
	"hrv_last_night_5min_high" integer,
	"hrv_weekly_avg" integer,
	"hrv_status" text,
	"sleep_score" integer,
	"sleep_duration_sec" integer,
	"deep_sleep_sec" integer,
	"light_sleep_sec" integer,
	"rem_sleep_sec" integer,
	"awake_sleep_sec" integer,
	"avg_sleep_stress" real,
	"avg_sleep_hr" real,
	"avg_sleep_respiration" real,
	"avg_stress" integer,
	"max_stress" integer,
	"bb_highest" integer,
	"bb_lowest" integer,
	"bb_charged" integer,
	"bb_drained" integer,
	"avg_waking_respiration" real,
	"avg_spo2" real,
	"lowest_spo2" real,
	"vo2_max" real,
	"completed" integer DEFAULT 0,
	"synced_at" text
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "argo"."exercises" (
	"id" text PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"category" text NOT NULL,
	"muscle_group" text NOT NULL,
	"is_bodyweight" integer DEFAULT 0,
	"display_order" integer DEFAULT 0
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "argo"."garmin_activities" (
	"activity_id" bigint PRIMARY KEY NOT NULL,
	"date" text NOT NULL,
	"start_time_local" text NOT NULL,
	"type_key" text NOT NULL,
	"activity_name" text,
	"duration_sec" real,
	"distance_m" real,
	"calories" integer,
	"avg_hr" real,
	"max_hr" integer,
	"aerobic_te" real,
	"anaerobic_te" real,
	"training_effect_label" text,
	"training_load" real,
	"moderate_intensity_min" integer,
	"vigorous_intensity_min" integer,
	"hr_zone_1_sec" real,
	"hr_zone_2_sec" real,
	"hr_zone_3_sec" real,
	"hr_zone_4_sec" real,
	"hr_zone_5_sec" real,
	"bb_delta" integer,
	"steps" integer,
	"vo2_max" real,
	"synced_at" text
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "argo"."sync_control" (
	"id" integer PRIMARY KEY DEFAULT 1 NOT NULL,
	"refresh_requested" integer DEFAULT 0,
	"requested_at" text,
	"in_progress" integer DEFAULT 0,
	"last_started_at" text,
	"last_completed_at" text,
	"last_status" text,
	"last_message" text
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "argo"."user_profile" (
	"id" integer PRIMARY KEY DEFAULT 1 NOT NULL,
	"height_cm" real,
	"birth_date" text,
	"gender" text,
	"goal_weight_kg" real,
	"updated_at" timestamp with time zone DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "argo"."weight_log" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "argo"."weight_log_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"date" text NOT NULL,
	"weight_kg" real NOT NULL,
	"created_at" timestamp with time zone DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "argo"."workout_sets" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "argo"."workout_sets_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"workout_id" integer NOT NULL,
	"set_number" integer NOT NULL,
	"set_type" text NOT NULL,
	"weight_kg" real NOT NULL,
	"reps" integer NOT NULL,
	"created_at" timestamp with time zone DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "argo"."workouts" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "argo"."workouts_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"date" text NOT NULL,
	"exercise_id" text NOT NULL,
	"notes" text,
	"created_at" timestamp with time zone DEFAULT now()
);
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "argo"."workout_sets" ADD CONSTRAINT "workout_sets_workout_id_workouts_id_fk" FOREIGN KEY ("workout_id") REFERENCES "argo"."workouts"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_garmin_activities_date" ON "argo"."garmin_activities" USING btree ("date");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_workout_sets_workout_id" ON "argo"."workout_sets" USING btree ("workout_id");