CREATE TABLE IF NOT EXISTS "argo"."skinfold_log" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "argo"."skinfold_log_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"date" text NOT NULL,
	"site" text NOT NULL,
	"value_mm" real NOT NULL,
	"created_at" timestamp with time zone DEFAULT now()
);
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "skinfold_log_date_site_uq" ON "argo"."skinfold_log" USING btree ("date","site");