CREATE TABLE IF NOT EXISTS "argo"."agent_narratives" (
	"project" text PRIMARY KEY NOT NULL,
	"summary" text NOT NULL,
	"page" text,
	"revised_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "argo"."agent_overview_snapshots" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "argo"."agent_overview_snapshots_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"machine" text NOT NULL,
	"generated_at" timestamp with time zone NOT NULL,
	"received_at" timestamp with time zone DEFAULT now() NOT NULL,
	"raw" jsonb NOT NULL
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_agent_overview_machine_received" ON "argo"."agent_overview_snapshots" USING btree ("machine","received_at" DESC NULLS LAST);